name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: node hello.js
      - run: npm install vitest
      - run: ls -la
      - run: npm run test
      - run: echo "test ok"
      - run: python3 -m pip install semgrep
      - run: semgrep scan
