name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 "
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ls -la
      - run: npm install
      - run: node hello.js
      - run: npm install -D vitest
      - run: npm run test
      