name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 "
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ls -la
      - name: Use Node.js
        uses: actions/setup-node@v4
      - run: node hello.js
      - run: npm i vitest
      - run: npm run test
      